# Generated by Django 4.1.5 on 2023-01-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idasia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=900)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_profile', to='idasia.profile')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies', to='idasia.replies'),
        ),
    ]
