# Generated by Django 4.1.5 on 2023-01-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idasia', '0003_alter_proj_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_files',
            name='file',
            field=models.FileField(blank=True, upload_to='./idasia/static/idasia/files/%Y/%m/%d'),
        ),
    ]
