# Generated by Django 4.1.5 on 2023-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idasia', '0005_remove_idea_proj_coauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='proj_cost',
            field=models.IntegerField(blank=True),
        ),
    ]
